In [2]:
import numpy as np

In [3]:
x=np.array([1, 6, 4, 78, 56])

In [4]:
print(x)

[ 1  6  4 78 56]


In [5]:
type(x)

numpy.ndarray

In [18]:
x.dtype

dtype('int64')

In [7]:
print(x.dtype)

int64


In [12]:
y=np.array([3.1742, 6.533, 4, 6, 90])

In [13]:
print(y)

[ 3.1742  6.533   4.      6.     90.    ]


In [14]:
y.dtype

dtype('float64')

In [15]:
print(y.dtype)

float64


In [16]:
np.save("my_array", y)

In [21]:
z=np.load("my_array.npy")

In [22]:
print(z)

[ 3.1742  6.533   4.      6.     90.    ]


In [24]:
z.ndim

1

In [25]:
print("rank of z np array is ", z.ndim)

rank of z np array is  1


In [6]:
a=np.array([[3.1742, 6.533, 4, 6, 90],[1, 6, 4, 78, 56],[3.1742, 6.533, 4, 6, 90],[1, 6, 4, 78, 56]])

In [29]:
a.ndim

2

In [30]:
a.dtype

dtype('float64')

In [39]:
b=np.array([[a,a,a,a],["Wewood", "Phase 1", "Phase 2", "TCN"]] dtype="")

/tmp/ipykernel_7506/2227438460.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[a,a,a,a],["Wewood", "Phase 1", "Phase 2", "TCN"]])


In [37]:
b.ndim

3

In [15]:
c=np.zeros([2,4,3,5], dtype=int)
print(c)
print("shape is ",c.shape)
print("nDimension is ", c.ndim)
print("size is ",c.size)
c.dtype

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]


 [[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]]]
shape is  (2, 4, 3, 5)
nDimension is  4
size is  120


dtype('int64')

In [17]:
Ones = np.ones([2,3])
print(Ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
Full_fives = np.full([3,4],7)
print(Full_fives)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [20]:
Identity_matrix = np.eye(5)
print(Identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
Diagonal_matrix = np.diag([1,2,3,5,8,13])
print(Diagonal_matrix)

[[ 1  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  0 13]]


In [23]:
Arange_stop = np.arange(7)
print(Arange)

[0 1 2 3 4 5 6]


In [24]:
Arange_start_stop = np.arange(3,10)
print(Arange_start_stop)

[3 4 5 6 7 8 9]


In [30]:
Arange_start_stop_step = np.arange(4,14,2)
print(Arange_start_stop_step)
'''arange function has problems with finite floating point decisions so when using non-integer steps, 
it's more advisable to use linspace function'''

[ 4  6  8 10 12]


"arange function has problems with finite floating point decisions so when using non-integer steps, \nit's more advisable to use linspace function"

In [10]:
Linspace_start_stop_step = np.linspace(4,20,6)
print(Linspace_start_stop_step)
'''While arange function uses rnge by adding the range to the previous value, linspace (start, stop, n) n value.
Unlike arange, stop is inclusive except outrightly specified (endPoint=False)
Where n isn't specified, it defaults to 50'''

[ 4.   7.2 10.4 13.6 16.8 20. ]


"While arange function uses rnge by adding the range to the previous value, linspace (start, stop, n) n value.\nUnlike arange, stop is inclusive except outrightly specified (endPoint=False)\nWhere n isn't specified, it defaults to 50"

In [12]:
Linspace_start_stop_step = np.linspace(4,20,6, endpoint=False)
print(Linspace_start_stop_step)


[ 4.          6.66666667  9.33333333 12.         14.66666667 17.33333333]


In [30]:
Reshape_d=np.array([2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32])
print(Reshape_d.size)
Reshape_d=np.reshape(Reshape_d,(4,4))
print(Reshape_d)
#reshape function changes an array into the specified shape as long as it 
#elements can fit into all positions of the shape.

16
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [31]:
Arange_Reshape = np.arange(20).reshape(4,5)
print(Arange_Reshape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [36]:
Linspace_Reshape = np.linspace(2,28,10, endpoint=False).reshape(5,2)
print(Linspace_Reshape)

[[ 2.   4.6]
 [ 7.2  9.8]
 [12.4 15. ]
 [17.6 20.2]
 [22.8 25.4]]


In [38]:
Random_random = np.random.random((3,5))
print(Random_random)

[[0.17820585 0.62771216 0.46887865 0.11983385 0.31920159]
 [0.89238255 0.35565822 0.06966259 0.76989795 0.59020988]
 [0.22312946 0.53424973 0.02896882 0.27187404 0.19898836]]


In [62]:
Random_randInt = np.random.randint(4,20,(3,4))
print(Random_randInt)

[[10 17 16 15]
 [15  9  5 19]
 [ 7  4 18  4]]


In [4]:
Random_mean_std = np.random.normal(0,0.5,size=(6,6))
print(Random_mean_std)
'''nomral function from the random module creates a random matrix with a specied mean (0 in this case) 
and standard deviation (0.1).'''
print("Mean of the matrix is ", Random_mean_std.mean())
print("Standard Deviation of the matrix is ", Random_mean_std.std())
print("Maximum of the matrix is ", Random_mean_std.max())
print("Minimum of the matrix is ", Random_mean_std.min())
print("Sum of number greater than 0  ", (Random_mean_std>0).sum())
print("Sum of number less than 0   ", (Random_mean_std<0).sum())

[[ 0.08688532  0.91307917 -0.2689959  -0.07167539  0.8393447   0.14219551]
 [-0.51141574  0.4117186   0.03898831 -0.11039357 -0.21737932 -0.2234551 ]
 [-0.66591246 -0.30804359  0.82325068 -0.60864803  0.34418171 -0.89411911]
 [ 0.16618576  0.23063349 -0.27653253 -0.46928321 -0.37716116 -0.32956829]
 [-0.01434206  0.72997315 -0.2940873   0.17102943  0.4536636  -0.09098083]
 [-0.63898404 -0.07250617  0.8426105   0.31840382  0.38484427 -0.34122018]]
Mean of the matrix is  0.003119001656083918
Standard Deviation of the matrix is  0.46158681596071216
Maximum of the matrix is  0.91307917155648
Minimum of the matrix is  -0.8941191072346866
Sum of number greater than 0   16
Sum of number less than 0    20


In [107]:
# Using the Built-in functions you learned about on the
# previous page, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.linspace(2,32,16, dtype=int).reshape(4,4)
print(X)
#Or
Y = np.arange(2,34,2).reshape(4,4)
print(Y)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [33]:
print(x)

[ 6  4 49]


In [15]:
print("index position 2 is",x[2])
print("index position -2 is",x[-2])
x[-2]=49
print(x)

index position 2 is 4
index position -2 is 78
[ 1  6  4 49 56]


In [24]:
print(Y)
print(Y[3,0])
Y[3,0]=45
print(Y[3])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [45 28 30 32]]
45
[45 28 30 32]


In [38]:
print(x)
Del_x_members=np.delete(x,[0,4])
print(Del_x_members)

[ 1  6  4 78 56]
[ 6  4 78]


In [43]:
print(Y)
Del_Y_row = np.delete(Y,[0,2], axis=0)
print(Del_Y_row)
Del_Y_column = np.delete(Y,[0,2], axis=1)
print(Del_Y_column)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [45 28 30 32]]
[[10 12 14 16]
 [45 28 30 32]]
[[ 4  8]
 [12 16]
 [20 24]
 [28 32]]


In [62]:
print(x)
Append_to_x = np.append(x,[32,56,21,14])
print(Append_to_x)
Reshape_x = np.reshape(Append_to_x,[3,3])
print(Reshape_x)
Append_row = np.append(Reshape_x,[[5,4,3]], axis=0)
print(Append_row)
Append_column = np.append(Reshape_x,[[17],[13],[11]], axis=1)
print(Append_column)

[ 1  6  4 78 56]
[ 1  6  4 78 56 32 56 21 14]
[[ 1  6  4]
 [78 56 32]
 [56 21 14]]
[[ 1  6  4]
 [78 56 32]
 [56 21 14]
 [ 5  4  3]]
[[ 1  6  4 17]
 [78 56 32 13]
 [56 21 14 11]]


In [63]:
# We insert a row between the first and last row of y
#w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
#v = np.insert(Y,1,5, axis=1)

In [100]:
print(Y)
Slicing_y = Y[0:2,1:3]
#Starts from the no. before the column and stopes before the number after the column. First Param is column, second is row.
print(Slicing_y)

Slicing_yy = Y[2:,2:]
# start:end. if start side is left blank, it starts from the beginning and stops at the last data if end is left blank. 
print(Slicing_yy)

Slicing_yyy = Y[:,2]
print(Slicing_yyy)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 12 24]
 [26 28 51 32]]
[[ 4  6]
 [12 14]]
[[12 24]
 [51 32]]
[ 6 14 12 51]


In [95]:
#when slicing, the varible being assigned to the sliced data isn't actually assigned. Its just showing a view of the portion of data.
#To actually make afresh assignment which can be altered without altering the original data set, .copy() method is used.

print(Y)
print("")
print(Slicing_yyy[3])
print("")
Slicing_yyy[3]=51
print(Slicing_yyy)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

30

[ 6 14 22 51]


In [96]:
print(Y)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 51 32]]


In [110]:
#In order not to alter Y when altering Slicing_yyy which is a subset of Y, we use the copy() method.
print(Y)
print("")
Slicing_yyyy= Y[:1,:].copy()
Slicing_yyyy[:1,1:2]=12
print(Slicing_yyyy)
print("")
print(Y)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

[[ 2 12  6  8]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [15]:
ee=np.arange(12)
print(ee)
print(ee[[ee>3] & [ee<10]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]


TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [17]:
Xx = np.arange(1,26).reshape(5,5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = Xx[Xx%2!=0]
print(Y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [61]:
#Boolean Indexing
g = np.arange(25).reshape(5, 5)

# We print g
print()
print('Original g = \n', g)
print()

# We use Boolean indexing to select elements in g:
print('The elements in g that are greater than 10:', g[g > 10])
print('The elements in g that less than or equal to 7:', g[g <= 7])
print('The elements in g that are between 10 and 17:', g[(g > 10) & (g < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
g[(g > 10) & (g < 17)] = -1

# We print g
print()
print('g = \n', g)


Original g = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in g that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in g that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in g that are between 10 and 17: [11 12 13 14 15 16]

g = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [62]:
#Set operations
# We create a rank 1 ndarray
h = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
i = np.array([6,7,2,8,4])

# We print h
print()
print('h = ', h)

# We print i
print()
print('i = ', i)

# We use set operations to compare h and i:
print()
print('The elements that are both in h and i:', np.intersect1d(h,i))
print('The elements that are in h that are not in i:', np.setdiff1d(h,i))
print('All the elements of h and i:',np.union1d(h,i))


h =  [1 2 3 4 5]

i =  [6 7 2 8 4]

The elements that are both in h and i: [2 4]
The elements that are in h that are not in i: [1 3 5]
All the elements of h and i: [1 2 3 4 5 6 7 8]


In [2]:
!conda list panda

# packages in environment at /home/jossy/anaconda3:
#
# Name                    Version                   Build  Channel
pandas                    1.4.2            py39h295c915_0  


In [3]:
import pandas as pd

In [39]:
fruits_colours = pd.Series(data=["Carrot","Apples","Water melons", "Mangoes", "Nuts"], 
                           index=["Orange","Green","Red", 4, 54])
fruits_colours

Orange          Carrot
Green           Apples
Red       Water melons
4              Mangoes
54                Nuts
dtype: object

In [5]:
fruits_colours.shape


(3,)

In [6]:
fruits_colours.size


3

In [7]:
fruits_colours.ndim

1

In [29]:
fruits_colours["Green"]
# Given the index "Green", this prints the corresponding data pair

'Apples'

In [27]:
fruits_colours[1]
# Given the index number, this prints the corresponding data pair

'Apples'

In [30]:
fruits_colours[[1,2]]
# Given the set of indices, this prints the corresponding data set

Green          Apples
Red      Water melons
dtype: object

In [40]:
#complications could arise when indices data set contain numbers in their dataset. To stem this confusion, the 
# .loc() sorts the actual data while .iloc() sort the data by index number of the data.
fruits_colours.iloc[4]

'Nuts'

In [41]:
fruits_colours.loc[4]

'Mangoes'

In [43]:
fruits_colours[["Red","Orange",4]]

Red       Water melons
Orange          Carrot
4              Mangoes
dtype: object

In [44]:
fruits_colours.drop(["Red"])


Orange     Carrot
Green      Apples
4         Mangoes
54           Nuts
dtype: object

In [45]:
fruits_colours

Orange          Carrot
Green           Apples
Red       Water melons
4              Mangoes
54                Nuts
dtype: object

In [46]:
fruits_colours.drop(["Red"], inplace=True)

In [47]:
fruits_colours

Orange     Carrot
Green      Apples
4         Mangoes
54           Nuts
dtype: object

In [49]:
#From the drop function above we see that .drop() only remove the index from that list. To totally expuange an
# index item, we add the inplace=True. This removes the index item from the original data set.

In [53]:
fruits= pd.Series([10, 6, 3,],['apples', 'oranges', 'bananas'])

# We display the fruits pandas Series
fruits

apples     10
oranges     6
bananas     3
dtype: int64

In [54]:
print('fruits + 2:\n', fruits + 2) # We add 2 to each item in fruits
print()
print('fruits - 2:\n', fruits - 2) # We subtract 2 to each item in fruits
print()
print('fruits * 2:\n', fruits * 2) # We multiply each item in fruits by 2 
print()
print('fruits / 2:\n', fruits / 2) # We divide each item in fruits by 2

fruits + 2:
 apples     12
oranges     8
bananas     5
dtype: int64

fruits - 2:
 apples     8
oranges    4
bananas    1
dtype: int64

fruits * 2:
 apples     20
oranges    12
bananas     6
dtype: int64

fruits / 2:
 apples     5.0
oranges    3.0
bananas    1.5
dtype: float64


In [59]:
print('EXP(X) = \n', np.exp(fruits))
print() 
print('SQRT(X) =\n', np.sqrt(fruits))
print()
print('POW(X,2) =\n',np.power(fruits,2))
#Note that these functions use numpy module and so should be imported.

EXP(X) = 
 apples     22026.465795
oranges      403.428793
bananas       20.085537
dtype: float64

SQRT(X) =
 apples     3.162278
oranges    2.449490
bananas    1.732051
dtype: float64

POW(X,2) =
 apples     100
oranges     36
bananas      9
dtype: int64


In [60]:
# We add 2 only to the bananas
print('Amount of bananas + 2 = ', fruits['bananas'] + 2)
print()

# We subtract 2 from apples using index locator
print('Amount of apples - 2 = ', fruits.iloc[0] - 2)
print()

# We multiply apples and oranges by 2
print('We double the amount of apples and oranges:\n', fruits[['apples', 'oranges']] * 2)
print()

# We divide apples and oranges by 2
print('We half the amount of apples and oranges:\n', fruits.loc[['apples', 'oranges']] / 2)

Amount of bananas + 2 =  5

Amount of apples - 2 =  8

We double the amount of apples and oranges:
 apples     20
oranges    12
dtype: int64

We half the amount of apples and oranges:
 apples     5.0
oranges    3.0
dtype: float64


In [98]:
item={"Jossy":pd.Series([35,40,22],['Shoe','Trouser','Shirt']),
      "Joy":pd.Series([12,21,24,50], ['Shorts','Shoe','Gown','Shirt'])}

DT_item = pd.DataFrame(item)

DT_item
#DataFrame represents a dictionary, key value-pairs in a tabular form.

Jossy   Joy
Gown       NaN  24.0
Shirt     22.0  50.0
Shoe      35.0  21.0
Shorts     NaN  12.0
Trouser   40.0   NaN

In [102]:
type(DT_item)

pandas.core.frame.DataFrame

In [84]:
type(item)

dict

In [88]:
'''There are several things to notice here, as explained below:

We see that DataFrames are displayed in tabular form, much like an Excel spreadsheet, with the labels of rows and columns in bold.

Also, notice that the row labels of the DataFrame are built from the union of the index labels of the two pandas Series we used to construct the dictionary. And the column labels of the DataFrame are taken from the keys of the dictionary.

Another thing to notice is that the columns are arranged alphabetically and not in the order given in the dictionary. We will see later that this won't happen when we load data into a DataFrame from a data file.

The last thing we want to point out is that we see some NaN values appear in the DataFrame. NaN stands for Not a Number, and is pandas' way of indicating that it doesn't have a value for that particular row and column index. For example, if we look at the column of Alice, we see that it has NaN in the watch index. You can see why this is the case by looking at the dictionary we created at the beginning. We clearly see that the dictionary has no item for Alice labeled watches. So whenever a DataFrame is created, if a particular column doesn't have values for a particular row index, pandas will put a NaN value there.

5. If we were to feed this data into a machine learning algorithm we will have to remove these NaN values first. In a later lesson, we will learn how to deal with NaN values and clean our data. For now, we will leave these values in our DataFrame.'''

"There are several things to notice here, as explained below:\n\nWe see that DataFrames are displayed in tabular form, much like an Excel spreadsheet, with the labels of rows and columns in bold.\n\nAlso, notice that the row labels of the DataFrame are built from the union of the index labels of the two pandas Series we used to construct the dictionary. And the column labels of the DataFrame are taken from the keys of the dictionary.\n\nAnother thing to notice is that the columns are arranged alphabetically and not in the order given in the dictionary. We will see later that this won't happen when we load data into a DataFrame from a data file.\n\nThe last thing we want to point out is that we see some NaN values appear in the DataFrame. NaN stands for Not a Number, and is pandas' way of indicating that it doesn't have a value for that particular row and column index. For example, if we look at the column of Alice, we see that it has NaN in the watch index. You can see why this is the 

In [89]:
data = {'Bob' : pd.Series([245, 25, 55]),
        'Alice' : pd.Series([40, 110, 500, 45])}

# We create a DataFrame
df = pd.DataFrame(data)

# We display the DataFrame
df
#When no index is available, the index starting for zero is automatically added.

Bob  Alice
0  245.0     40
1   25.0    110
2   55.0    500
3    NaN     45

In [104]:
DT_item

Jossy   Joy
Gown       NaN  24.0
Shirt     22.0  50.0
Shoe      35.0  21.0
Shorts     NaN  12.0
Trouser   40.0   NaN

In [105]:
# We print some information about shopping_carts
print('items has shape:', DT_item.shape)
print('items has dimension:', DT_item.ndim)
print('items has a total of:', DT_item.size, 'elements')
print()
print('The data in items is:\n', DT_item.values)
print()
print('The row index in items is:', DT_item.index)
print()
print('The column index in items is:', DT_item.columns)

items has shape: (5, 2)
items has dimension: 2
items has a total of: 10 elements

The data in items is:
 [[nan 24.]
 [22. 50.]
 [35. 21.]
 [nan 12.]
 [40. nan]]

The row index in items is: Index(['Gown', 'Shirt', 'Shoe', 'Shorts', 'Trouser'], dtype='object')

The column index in items is: Index(['Jossy', 'Joy'], dtype='object')


In [107]:
# We Create a DataFrame that only has Bob's data
Jossy_shopping_cart = pd.DataFrame(DT_item, columns=['Jossy'])

# We display bob_shopping_cart
Jossy_shopping_cart

Jossy
Gown       NaN
Shirt     22.0
Shoe      35.0
Shorts     NaN
Trouser   40.0

In [108]:
#Selecting specific rows of a DataFrame
# We Create a DataFrame that only has selected items for both Alice and Bob
sel_shopping_cart = pd.DataFrame(DT_item, index = ['Shirt', 'Gown'])

# We display sel_shopping_cart
sel_shopping_cart

Jossy   Joy
Shirt   22.0  50.0
Gown     NaN  24.0

In [109]:
#Create a DataFrame using a dictionary of lists
# We create a dictionary of lists (arrays)
num_data = {'Integers' : [1,2,3],
        'Floats' : [4.5, 8.2, 9.6]}

# We create a DataFrame 
dF = pd.DataFrame(num_data)

# We display the DataFrame
dF

Integers  Floats
0         1     4.5
1         2     8.2
2         3     9.6

In [110]:
 #Create a DataFrame using a dictionary of lists, and custom row-indexes (labels)
# We create a dictionary of lists (arrays)
data_with_labels = {'Integers' : [1,2,3],
        'Floats' : [4.5, 8.2, 9.6]}

# We create a DataFrame and provide the row index
dFf = pd.DataFrame(data_with_labels, index = ['label 1', 'label 2', 'label 3'])

# We display the DataFrame
dFf

Integers  Floats
label 1         1     4.5
label 2         2     8.2
label 3         3     9.6

In [111]:
#Create a DataFrame using a of list of dictionaries
# We create a list of Python dictionaries
items2 = [{'bikes': 20, 'pants': 30, 'watches': 35}, 
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}]

# We create a DataFrame 
store_items = pd.DataFrame(items2)

# We display the DataFrame
store_items

bikes  pants  watches  glasses
0     20     30       35      NaN
1     15      5       10     50.0

In [112]:
#Create a DataFrame using a of list of dictionaries, and custom row-indexes (labels)
# We create a list of Python dictionaries
items3 = [{'bikes': 20, 'pants': 30, 'watches': 35}, 
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}]

# We create a DataFrame  and provide the row index
store_items2 = pd.DataFrame(items3, index = ['store 1', 'store 2'])

# We display the DataFrame
store_items2

bikes  pants  watches  glasses
store 1     20     30       35      NaN
store 2     15      5       10     50.0

In [113]:
#Create a row to be added to the DataFrame
# We create a dictionary from a list of Python dictionaries that will contain the number of different items at the new store
new_items = [{'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4}]

# We create new DataFrame with the new_items and provide and index labeled store 3
new_store = pd.DataFrame(new_items, index = ['store 3'])

# We display the items at the new store
new_store

bikes  pants  watches  glasses
store 3     20     30       35        4

In [117]:
#Append the row to the DataFrame
# We append store 3 to our store_items DataFrame
store_items = store_items2.append(new_store)

# We display the modified DataFrame
store_items

/tmp/ipykernel_6405/2963285931.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  store_items = store_items2.append(new_store)


bikes  pants  watches  glasses
store 1     20     30       35      NaN
store 2     15      5       10     50.0
store 3     20     30       35      4.0

In [118]:
#Add new column that has data from the existing columns
# We add a new column using data from particular rows in the watches column
store_items['new watches'] = store_items['watches'][1:]

# We display the modified DataFrame
store_items

bikes  pants  watches  glasses  new watches
store 1     20     30       35      NaN          NaN
store 2     15      5       10     50.0         10.0
store 3     20     30       35      4.0         35.0

In [119]:
#Delete one column from a DataFrame
# We remove the new watches column
store_items.pop('new watches')

# we display the modified DataFrame
store_items

bikes  pants  watches  glasses
store 1     20     30       35      NaN
store 2     15      5       10     50.0
store 3     20     30       35      4.0

In [121]:
#Delete multiple columns from a DataFrame
# We remove the watches and shoes columns
store_items = store_items.drop(['watches', 'pants'], axis = 1)

#axis = 1 is for coulumns while axis = 0 is for rows
# we display the modified DataFrame
store_items

bikes  glasses
store 1     20      NaN
store 2     15     50.0
store 3     20      4.0

In [122]:
#Delete rows from a DataFrame
# We remove the store 2 and store 1 rows
store_items = store_items.drop(['store 2', 'store 1'], axis = 0)

# we display the modified DataFrame
store_items

bikes  glasses
store 3     20      4.0

In [123]:
#Modify the column label
# We change the column label bikes to hats
store_items = store_items.rename(columns = {'bikes': 'hats'})

# we display the modified DataFrame
store_items

hats  glasses
store 3    20      4.0

In [124]:
#Modify the row label
# We change the row label from store 3 to last store
store_items = store_items.rename(index = {'store 3': 'last store'})

# we display the modified DataFrame
store_items

hats  glasses
last store    20      4.0